FROM openjdk:8
ENV name=AMMA
#CMD echo "OM MY DEAR, ${name}"
#ENTRYPOINT ["/bin/echo", "PONNA AMMA $name"]
#RUN echo "AMMA from RUN , ${name}"
ENTRYPOINT echo "AMMA from ENTRY $name"
#CMD echo "AMMA from CMD, ${name}"