version: '3.2'

networks:
  kafka-net:
    #external: true
    attachable: true
    driver: overlay

services:
 zookeeper-1:
   image: confluentinc/cp-zookeeper:latest
   hostname: zookeeper-1
   container_name: zookeeper-1
   environment:
     ZOOKEEPER_SERVER_ID: 1
     ZOOKEEPER_CLIENT_PORT: 22181
     ZOOKEEPER_TICK_TIME: 2000
     ZOOKEEPER_INIT_LIMIT: 5
     ZOOKEEPER_SYNC_LIMIT: 2
     KAFKA_ZOOKEEPER_TIMEOUT_MS: 36000
     ZOOKEEPER_SERVERS: zookeeper-1:22888:23888;zookeeper-2:32888:33888;zookeeper-3:42888:43888
   ports:
     -  "22181:22181"     
   network_mode: global
   networks:
    - kafka-net
 
 zookeeper-2:
   image: confluentinc/cp-zookeeper:latest
   hostname: zookeeper-2
   container_name: zookeeper-2
   environment:
     ZOOKEEPER_SERVER_ID: 2
     ZOOKEEPER_CLIENT_PORT: 32181
     ZOOKEEPER_TICK_TIME: 2000
     ZOOKEEPER_INIT_LIMIT: 5
     ZOOKEEPER_SYNC_LIMIT: 2
     KAFKA_ZOOKEEPER_TIMEOUT_MS: 36000
     ZOOKEEPER_SERVERS: zookeeper-1:22888:23888;zookeeper-2:32888:33888;zookeeper-3:42888:43888
   ports:
     -  "32181:32181"
   network_mode: global
   networks:
    - kafka-net

 
 zookeeper-3:
   image: confluentinc/cp-zookeeper:latest
   hostname: zookeeper-3
   container_name: zookeeper-3
   environment:
     ZOOKEEPER_SERVER_ID: 3
     ZOOKEEPER_CLIENT_PORT: 42181
     ZOOKEEPER_TICK_TIME: 2000
     ZOOKEEPER_INIT_LIMIT: 5
     ZOOKEEPER_SYNC_LIMIT: 2
     KAFKA_ZOOKEEPER_TIMEOUT_MS: 36000
     ZOOKEEPER_SERVERS: zookeeper-1:22888:23888;zookeeper-2:32888:33888;zookeeper-3:42888:43888
   ports:
     -  "42181:42181"
   network_mode: global
   networks:
    - kafka-net

 kafka-1:
   image: confluentinc/cp-kafka:latest
   hostname: kafka-1
   network_mode: global
   networks:
    - kafka-net
   depends_on:
     -  zookeeper-1
     -  zookeeper-2
     -  zookeeper-3
   environment:
     KAFKA_BROKER_ID: 1
     KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:22181,zookeeper-2:32181,zookeeper-3:42181
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:19090
   ports:
     -  "19090:19090"

 
 kafka-2:
   image: confluentinc/cp-kafka:latest
   hostname: kafka-2
   network_mode: global
   networks:
    - kafka-net
   depends_on:
     -  zookeeper-1
     -  zookeeper-2
     -  zookeeper-3
   environment:
     KAFKA_BROKER_ID: 2
     KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:22181,zookeeper-2:32181,zookeeper-3:42181
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:19091
   ports:
     -  "19091:19091"

 
 kafka-3:
   image: confluentinc/cp-kafka:latest
   hostname: kafka-3
   network_mode: global
   networks:
    - kafka-net
   depends_on:
     -  zookeeper-1
     -  zookeeper-2
     -  zookeeper-3
   environment:
     KAFKA_BROKER_ID: 3
     KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:22181,zookeeper-2:32181,zookeeper-3:42181
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:19092
   ports:
     -  "19092:19092"
